name: OST ds

on:
  issue_comment:
    types: [created]

jobs:
  trigger-ost:
    if: |
      github.event.issue.pull_request &&
      github.event.comment.body == '/ost' &&
      (
        github.event.comment.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'COLLABORATOR'
      )
    uses: oVirt/ovirt-system-tests/.github/workflows/ost.yaml@master
    with:
      pr_url: ${{ github.event.issue.pull_request.url }}
      comment: " basic-suite-master rhel8"
